//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionProcam.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDetail
    {
        public tblEmployeeDetail()
        {
            this.tblAssetIssueDetails = new HashSet<tblAssetIssueDetail>();
        }
    
        public int ID { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpDesignation { get; set; }
        public string EmpDept { get; set; }
        public string PhoneNo { get; set; }
    
        public virtual ICollection<tblAssetIssueDetail> tblAssetIssueDetails { get; set; }
    }
}
